apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: capstone-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: capstone
              servicePort: 80