AWSTemplateFormatVersion: "2010-09-09"
Description: EKS - Node Group

Resources:
  EKSNodegroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      AmiType: AL2_x86_64
      ClusterName: !ImportValue ClusterName
      DiskSize: 20
      InstanceTypes:
        - t3.medium
      Labels:
        Name: cdnCapstoneNodeGroup
        Scope: UdacityCloudDevopsEngineeringNanodegree
      NodeRole: !ImportValue eksNodeInstanceRole
      RemoteAccess:
        Ec2SshKey: eks-capstone
      ScalingConfig:
        MinSize: 2
        DesiredSize: 2
        MaxSize: 4
      Subnets:
        - subnet-043c525222259b345
        - subnet-09807f825bf967207
      Tags:
        Key: Scope
        Value: UdacityCloudDevopsEngineeringNanodegree